application: go-playground
version: 1
runtime: go
api_version: 3

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /(|compile|share)
  script: _go_app
- url: /p/.+
  script: _go_app
